services:
  - type: web
    name: shadowchat
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn shadowchat:app -k eventlet -w 1
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
